-- Psychology module test database tables for H2
-- 心理模块测试数据库表结构（H2兼容版本）

-- ----------------------------
-- Table structure for lvye_questionnaire
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_questionnaire" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(255) NOT NULL,
    "description" varchar(2000),
    "questionnaire_type" tinyint NOT NULL,
    "target_audience" tinyint NOT NULL,
    "external_id" varchar(100),
    "external_link" varchar(500),
    "question_count" int,
    "estimated_duration" int,
    "content" varchar(10000),
    "scoring_rules" varchar(2000),
    "result_template" varchar(2000),
    "status" tinyint DEFAULT 0,
    "is_open" tinyint DEFAULT 1,
    "sort_order" int DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id")
);


-- ----------------------------
-- Table structure for lvye_questionnaire_result_config
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_questionnaire_result_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "questionnaire_id" bigint NOT NULL,
    "dimension_name" varchar(255) NOT NULL,
    "question_index" varchar(255),
    "calculate_type" int,
    "calculate_formula" varchar(2000),
    "teacher_comment" varchar(2000),
    "student_comment" varchar(2000),
    "is_abnormal" int DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Table structure for lvye_assessment_scenario
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_assessment_scenario" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(128) NOT NULL,
    "max_questionnaire_count" int,
    "frontend_route" varchar(128) NOT NULL,
    "is_active" bit NOT NULL DEFAULT TRUE,
    "metadata_json" varchar(2000),
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Table structure for lvye_assessment_scenario_slot
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_assessment_scenario_slot" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "scenario_id" bigint NOT NULL,
    "slot_key" varchar(64) NOT NULL,
    "slot_name" varchar(128) NOT NULL,
    "slot_order" int NOT NULL DEFAULT 0,
    "allowed_questionnaire_types" varchar(256),
    "frontend_component" varchar(128),
    "metadata_json" varchar(2000),
    "questionnaire_id" bigint,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Table structure for lvye_assessment_task
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_assessment_task" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "task_no" varchar(64) NOT NULL,
    "task_name" varchar(120),
    "target_audience" tinyint,
    "status" tinyint DEFAULT 0,
    "publish_user_id" bigint,
    "startline" datetime,
    "deadline" datetime,
    "scenario_id" bigint,
    "description" varchar(2000),
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id"),
    UNIQUE KEY "idx_task_no" ("task_no", "tenant_id")
);

-- ----------------------------
-- Table structure for lvye_assessment_task_questionnaire
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_assessment_task_questionnaire" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "task_no" varchar(64) NOT NULL,
    "questionnaire_id" bigint NOT NULL,
    "slot_key" varchar(64),
    "slot_order" int,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Table structure for lvye_assessment_result
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_assessment_result" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "questionnaire_results" varchar(5000),
    "combined_risk_level" tinyint,
    "risk_factors" varchar(2000),
    "intervention_suggestions" varchar(2000),
    "generation_config_version" varchar(50),
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id")
);

-- ----------------------------
-- Table structure for lvye_student_profile
-- ----------------------------
CREATE TABLE IF NOT EXISTS "lvye_student_profile" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "student_id" bigint NOT NULL,
    "name" varchar(100),
    "sex" tinyint,
    "creator" varchar(64) DEFAULT '',
    "create_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" datetime DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint DEFAULT 0,
    PRIMARY KEY ("id")
);
