# 参考: https://cnb.cool/examples/ecosystem/springboot-maven-ssh
main:
  push:
    - name: Build Spring Boot Application
      services:
        - docker
      env:
        JAVA_VERSION: 17
      # 导入环境变量配置文件（用于 SSH 部署）
      imports: https://cnb.cool/mindfront/psychology/deploy-credentials/-/blob/main/mindtrip-psychology-backend-envs.yml
      caches:
        - path: ~/.m2/repository
      stages:
        - name: Setup JDK ${JAVA_VERSION}
          script: |
            apt-get update -y
            apt-get install -y openjdk-${JAVA_VERSION}-jdk
            export JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            java -version

        - name: Install Maven
          script: |
            apt-get install -y maven
            mvn -version

        - name: Restore Maven Cache
          script: |
            if [ -d ~/.m2/repository ]; then
              echo "Maven cache restored"
            else
              mkdir -p ~/.m2/repository
              echo "Maven cache directory created"
            fi

        - name: Build with Maven
          script: |
            # 从根目录构建整个项目（会自动处理所有模块依赖）
            mvn clean install -Dmaven.test.skip=true

        # - name: Build Docker Image
        #   script: |
        #     cd yudao-server
        #     docker build -t yudao-server:latest .

        # SSH 部署阶段（可选，需要在 CNB 平台配置环境变量）
        # - name: Deploy via SSH
        #   plugins:
        #     - name: ssh
        #       config:
        #         host: ${REMOTE_HOST}
        #         user: ${REMOTE_USERNAME}
        #         port: ${REMOTE_PORT}
        #         privateKey: ${PRIVATE_KEY}
        #       script: |
        #         # 部署 Docker 镜像或上传文件
        #         echo "Deploying to remote server..."