# 参考: https://cnb.cool/examples/ecosystem/springboot-maven-ssh
# 缓存优化文档: https://docs.cnb.cool/zh/build/pipeline-cache.html
main:
  push:
    - name: Build Spring Boot Application
      # 使用官方 Maven 镜像，包含 JDK 和 Maven，避免每次安装
      image: maven:3.9-eclipse-temurin-17
      services:
        - docker
      env:
        MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
      # 导入环境变量配置文件（用于 SSH 部署）
      imports: https://cnb.cool/mindfront/psychology/deploy-credentials/-/blob/main/mindtrip-psychology-backend-envs.yml
      # 配置缓存目录
      runner:
        volumes:
          - /cache/.m2/repository
      stages:
        - name: Verify Environment
          script: |
            java -version
            mvn -version
            echo "Maven repository: /cache/.m2/repository"

        - name: Build with Maven
          script: |
            # 从根目录构建整个项目（会自动处理所有模块依赖）
            mvn clean install -Dmaven.test.skip=true

        # - name: Build Docker Image
        #   script: |
        #     cd yudao-server
        #     docker build -t yudao-server:latest .

        # SSH 部署阶段（可选，需要在 CNB 平台配置环境变量）
        - name: Deploy via SSH
          plugins:
            - name: ssh
              config:
                host: ${REMOTE_HOST}
                user: ${REMOTE_USERNAME}
                port: ${REMOTE_PORT}
                privateKey: ${PRIVATE_KEY}
              script: |
                # 部署 Docker 镜像或上传文件
                echo "Deploying to remote server..."